FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime
RUN apt-get update && apt-get install -y git wget && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/comfyanonymous/ComfyUI.git /app
WORKDIR /app
RUN pip install -r requirements.txt
# Permitimos montar la carpeta models desde el host
CMD ["python", "main.py", "--listen"]
